### ISSUE TITLE
Some little bugs and illogical things

### ISSUE THREAD

**Issue by 1justsomeone1** [TeamOct/fictional-octo-system#26]
1. Sticker attacks ground units instead of air
![IMG_20240502_160836](https://github.com/TeamOct/fictional-octo-system/assets/168733027/6d6797d4-34a8-429e-88b8-11aa945ebe09)
2. Draug can shoot lol
![Screenshot_2024-05-02-15-53-34-79_13f989b68d7412e5a177fb13b36ac66f](https://github.com/TeamOct/fictional-octo-system/assets/168733027/7fc71820-af85-489b-b8aa-be8e0d7df321)
3. rotated tin belts have little bug in texture
![IMG_20240502_164152](https://github.com/TeamOct/fictional-octo-system/assets/168733027/74373286-b830-4b07-8bb3-704075181a8c)
4. If you blow up surface detonator near the map border game will close
5. Bug spawners dont become derelict at 
Conflict. Also bugs sometimes get stuck in spawners or walls
![IMG_20240502_233025](https://github.com/TeamOct/fictional-octo-system/assets/168733027/2f0c1722-5672-43d9-b451-bafb3c6ae2f5)
![IMG_20240502_233036](https://github.com/TeamOct/fictional-octo-system/assets/168733027/c7c2e171-f5ee-4efc-9766-2d4d0a82482a)

And by the way, did I do the right thing by writing all these things in one issue, or I have to post them separately? And sorry for my English

**Comment by Slotterleet** [comment]
fixed
