### ISSUE TITLE
Wave times are broken

### ISSUE THREAD

**Issue by beastcannon2** [TeamOct/fictional-octo-system#28]
![image_2024-06-19_115807006](https://github.com/TeamOct/FOS/assets/56883013/b49505ef-553d-4789-9e5a-4289eb662c22)
about 6m Into citadel and a wave of these armored bugs swarm me before I can even get my economy together (I already killed like half of them) 
I feel like theres something im missing but I dont even have the chance to look around the map before I get stampeded and sent to the game over screen.

**Comment by Slotterleet** [comment]
1. Non-wave spawning of bugs is intentional.
2. Abundance of these bugs in Citadel is a known issue, already resolved and the patch will take place in the next update.
