### ISSUE TITLE
Stuck on the first level of the campaign.

### ISSUE THREAD

**Issue by Proudsnow98** [TeamOct/fictional-octo-system#29]
I downloaded the mod, fired it up, and started playing it's campaign. I got a little bit through it and was researching stuff before the enemy spawns, as usual (I like to get a headstart). I was on the part where you're supposed to place 6 crude drills. I had already placed two, and I turned off my phone because I had something to do. When I got back, I turned it on, and booted up mindustry again. I went back to the campaign, and saw that it said Wave 0/2 waiting. I was confused, so I went to the enemy spawn, and destroyed the bug nest, releasing insect units. I killed them, but the wave didn't change. I can't progress to the next level because of the waves. Anything I can do?
I play on a Samsung S23 Ultra.
![Screenshot_20240703_211244_Mindustry](https://github.com/TeamOct/FOS/assets/174665321/b25a28d6-c692-4cf6-8134-b514f66ecefe)
Thanks for your time!

**Comment by Slotterleet** [comment]
That's... strange. When I tried to reproduce your problem, the objectives just reset on my side.

Try to do this:
1. Go to campaign **from the main menu**.
2. Select Awakening, but do not enter it just yet.
3. Press "Stats" below, then "Abandon" - this will clear your broken save.
4. Retry this sector.

**Comment by Proudsnow98** [comment]
I did that many times, but the only thing changed is that it said 1/2 instead of 0/2. The bug nest didn't respawn.

**Comment by Proudsnow98** [comment]
Nevermind, just updated it, works now. Thanks!
