### ISSUE TITLE
Can't research the drill base for some reason

### ISSUE THREAD

**Issue by kapzduke** [TeamOct/fictional-octo-system#3]
![image](https://user-images.githubusercontent.com/60543005/189992084-1f232dd8-fac4-40c0-b435-43b3e2c7b9e9.png)
is there a quick js command to fix this?

**Comment by Slotterleet** [comment]
Could you please provide more details about this issue?

**Comment by kapzduke** [comment]
theres nothing more i can tell, i fired up fos, landed on the beginning but it was not there.

**Comment by Slotterleet** [comment]
Don't you have to research it while playing the tutorial?

**Comment by kapzduke** [comment]
i was stuck on the "research drill base" task

**Comment by Slotterleet** [comment]
What exactly stops you from researching it?

**Comment by kapzduke** [comment]
....it not being on the tech tree

**Comment by Slotterleet** [comment]
I think I get it now. You might have not have the core researched, and the drill base goes after the core. For now, wait for more updates.
