### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Murky651** [TeamOct/fictional-octo-system#30]
So I am playing the 2nd map when the boss for wave 1 spawns, and my game crashes. I got an error message saying something like "bossMusic = null" or something like that. I will try to recreate it and send a screen shot of the error.

**Comment by Slotterleet** [comment]
Crash log is **required.**

**Comment by Murky651** [comment]
Imma keep trying, but I could not recreate it. I will post it here if I find anything.

**Comment by Slotterleet** [comment]
> Imma keep trying, but I could not recreate it. I will post it here if I find anything.

You must provide the latest crash report found in `.../Mindustry/crashes` directory, or I'll close this issue.

**Comment by Murky651** [comment]
Sorry. I cant find it. If I recreate it, I will open up one more issue with the same thing.
