### ISSUE TITLE
Can't finish the tutorial 

### ISSUE THREAD

**Issue by zef126** [TeamOct/fictional-octo-system#31]
The tutorial just stopped giving me instructions at the Upgrade centre research and he didn't let me continue!

PS: To be the only to defend, without turrets or other bots, is not the spirit of Mindustry, I hope it is not the case.

**Comment by Slotterleet** [comment]
Just research (and place) the upgrade center, what's the problem?

**Comment by zef126** [comment]
It block there!
![Screenshot_2024-08-20-17-49-48-777_io.anuke.mindustry.jpg](https://github.com/user-attachments/assets/973a1208-9c4a-45ca-bf5b-816b83249b1b)

**Comment by Slotterleet** [comment]
Other mods have definitely affected this save...
![изображение](https://github.com/user-attachments/assets/67d66bbc-4827-48ee-87c3-561e33531758)
There's no other option except:
1. Going back to **main menu** - this is important!.
2. Selecting Awakening sector again, but not going to it yet.
3. Press the Stats button below, then press Abandon - this will erase this map's save.
4. Re-launching to the sector.

**Comment by zef126** [comment]
Ok

**Comment by zef126** [comment]
It didn't work!

**Comment by Slotterleet** [comment]
Have you followed all the steps properly? Mind you, you need to abandon after **going back to main menu.**

**Comment by zef126** [comment]
Yeah I did!

**Comment by Slotterleet** [comment]
At this point I need your savefile. Settings > Game Data > Export. I don't know what else to say about this.

**Comment by zef126** [comment]
I did the first procedure again and it worked!

**Comment by zef126** [comment]
Thanks!

**Comment by zef126** [comment]
An other question, is it normal that the bot get always stuck?

**Comment by Slotterleet** [comment]
What bot?

**Comment by zef126** [comment]
Your character that is building!

**Comment by Kev-Vily** [comment]
> Your character that is building!

that is a core unit. oh god bruh
the core unit wasn't stuck, it cannot Pathfinding it self, because we are who controlling it. it's because the core unit was a ground unit.

**Comment by Slotterleet** [comment]
Core units are legged. I don't even know how you can call this a bug.
