### ISSUE TITLE
Vulnerable textures

### ISSUE THREAD

**Issue by zef126** [TeamOct/fictional-octo-system#32]
When other mods are installed, some texture pack dosapear (ex. Project HPL).

**Comment by Slotterleet** [comment]
For this one we require screenshots. We don't even _know_ how is breaking other mods' textures even possible.

**Comment by zef126** [comment]
![Screenshot_2024-08-20-08-42-43-005_io.anuke.mindustry.jpg](https://github.com/user-attachments/assets/9a78a30a-ade2-45cf-8bed-a7260563039a)

**Comment by Slotterleet** [comment]
Works fine on my end. The first screenshot is FOS, the other is HPL.
![Screenshot_20240820_100213_io anuke mindustry](https://github.com/user-attachments/assets/24964dbe-a361-4936-92b8-bd09f7996e05)
![Screenshot_20240820_100229_io anuke mindustry](https://github.com/user-attachments/assets/543c977c-930e-4ae0-86f7-a9123e9f8a7e)

1. Make sure you have no _other_ mods that could break your game. Actually, I'd want a full list of mods you've enabled so far.
2. If there appears to be no other mods breaking the textures, try reinstalling both FOS and HPL.

**Comment by zef126** [comment]
You are right, the problem is New Horizons
