### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by yesC48** [TeamOct/fictional-octo-system#33]
### Platforms

Android

### Game Build

bleeding-edge 25128

### Mod Build / Version

1.1 beta build-2.2

### Issue

landing on Awakening sector crashes the game

### Steps to reproduce

enter the sector...

### Mods used

fos
> fos ost omitted

### Save file

[files.zip](https://github.com/user-attachments/files/16711345/files.zip)

### (Crash) logs

[crash_1724333009717.txt](https://github.com/user-attachments/files/16711308/crash_1724333009717.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/TeamOct/FOS/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am sure that the bug is not caused by other mods I have installed, or, in rare cases, the game itself.

**Comment by Slotterleet** [comment]
Yes, yet another abstract method error report. FOS is not being supported for BE versions right now.
